Imagine you working as a sale manager now you need to predict the Revenue and whether that particular revenue is on the weekend or not and find the Informational_Duration using the Ensemble learning algorithm

In [ ]:
import pandas as pd
df = pd.read_csv("/content/online_shoppers_intention.csv")
df.head(50)

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.000000,0.100000,0.000000,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.050000,0.140000,0.000000,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.020000,0.050000,0.000000,0.0,Feb,3,3,1,4,Returning_Visitor,True,False
5,0,0.0,0,0.0,19,154.216667,0.015789,0.024561,0.000000,0.0,Feb,2,2,1,3,Returning_Visitor,False,False
6,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.4,Feb,2,4,3,3,Returning_Visitor,False,False
7,1,0.0,0,0.0,0,0.000000,0.200000,0.200000,0.000000,0.0,Feb,1,2,1,5,Returning_Visitor,True,False
8,0,0.0,0,0.0,2,37.000000,0.000000,0.100000,0.000000,0.8,Feb,2,2,2,3,Returning_Visitor,False,False
9,0,0.0,0,0.0,3,738.000000,0.000000,0.022222,0.000000,0.4,Feb,2,4,1,2,Returning_Visitor,False,False
10,0,0.0,0,0.0,3,395.000000,0.000000,0.066667,0.000000,0.0,Feb,1,1,3,3,Returning_Visitor,False,False
11,0,0.0,0,0.0,16,407.750000,0.018750,0.025833,0.000000,0.4,Feb,1,1,4,3,Returning_Visitor,False,False
12,0,0.0,0,0.0,7,280.500000,0.000000,0.028571,0.000000,0.0,Feb,1,1,1,3,Returning_Visitor,False,False
13,0,0.0,0,0.0,6,98.000000,0.000000,0.066667,0.000000,0.0,Feb,2,5,1,3,Returning_Visitor,False,False
14,0,0.0,0,0.0,2,68.000000,0.000000,0.100000,0.000000,0.0,Feb,3,2,3,3,Returning_Visitor,False,False
15,2,53.0,0,0.0,23,1668.285119,0.008333,0.016313,0.000000,0.0,Feb,1,1,9,3,Returning_Visitor,False,False
16,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,Feb,1,1,4,3,Returning_Visitor,False,False
17,0,0.0,0,0.0,13,334.966667,0.000000,0.007692,0.000000,0.0,Feb,1,1,1,4,Returning_Visitor,True,False
18,0,0.0,0,0.0,2,32.000000,0.000000,0.100000,0.000000,0.0,Feb,2,2,1,3,Returning_Visitor,False,False
19,0,0.0,0,0.0,20,2981.166667,0.000000,0.010000,0.000000,0.0,Feb,2,4,4,4,Returning_Visitor,False,False
20,0,0.0,0,0.0,8,136.166667,0.000000,0.008333,0.000000,1.0,Feb,2,2,5,1,Returning_Visitor,True,False
21,0,0.0,0,0.0,2,0.000000,0.200000,0.200000,0.000000,0.0,Feb,3,3,1,3,Returning_Visitor,False,False
22,0,0.0,0,0.0,3,105.000000,0.000000,0.033333,0.000000,0.0,Feb,3,2,1,5,Returning_Visitor,False,False
23,0,0.0,0,0.0,2,15.000000,0.000000,0.100000,0.000000,0.8,Feb,2,4,1,3,Returning_Visitor,False,False
24,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,Feb,2,2,4,1,Returning_Visitor,True,False
25,0,0.0,0,0.0,5,156.000000,0.000000,0.040000,0.000000,0.0,Feb,1,1,9,3,Returning_Visitor,False,False
26,4,64.6,0,0.0,32,1135.444444,0.002857,0.009524,0.000000,0.0,Feb,2,2,1,3,Returning_Visitor,False,False
27,0,0.0,0,0.0,4,76.000000,0.050000,0.100000,0.000000,0.0,Feb,1,1,1,3,Returning_Visitor,False,False
28,0,0.0,0,0.0,4,63.000000,0.000000,0.050000,0.000000,0.2,Feb,2,6,1,3,Returning_Visitor,False,False
29,1,6.0,1,0.0,45,1582.750000,0.043478,0.050821,54.179764,0.4,Feb,3,2,1,1,Returning_Visitor,False,False
30,0,0.0,0,0.0,2,35.000000,0.000000,0.100000,0.000000,0.0,Feb,1,1,6,3,Returning_Visitor,False,False
31,0,0.0,0,0.0,3,78.000000,0.000000,0.066667,0.000000,0.0,Feb,1,2,6,6,Returning_Visitor,True,False
32,0,0.0,0,0.0,8,209.500000,0.000000,0.025000,0.000000,0.0,Feb,2,2,1,1,Returning_Visitor,False,False
33,0,0.0,0,0.0,10,183.666667,0.040000,0.080000,0.000000,0.0,Feb,1,1,3,1,Returning_Visitor,False,False
34,0,0.0,0,0.0,14,380.500000,0.014286,0.028571,0.000000,0.0,Feb,2,2,1,1,Returning_Visitor,False,False
35,0,0.0,0,0.0,52,2086.242857,0.015385,0.020353,0.000000,0.0,Feb,2,2,7,1,Returning_Visitor,False,False
36,0,0.0,0,0.0,8,388.000000,0.025000,0.056250,0.000000,0.0,Feb,3,2,1,4,Returning_Visitor,True,False
37,2,18.0,0,0.0,5,298.000000,0.000000,0.028571,0.000000,0.8,Feb,2,2,8,4,Returning_Visitor,False,False
38,0,0.0,0,0.0,7,63.000000,0.028571,0.071429,0.000000,0.6,Feb,2,2,1,3,Returning_Visitor,False,False
39,0,0.0,0,0.0,9,482.000000,0.000000,0.022222,0.000000,0.0,Feb,2,5,1,6,Returning_Visitor,False,False
40,1,9.0,0,0.0,46,4084.393939,0.000000,0.001795,0.000000,0.0,Feb,2,2,8,4,Returning_Visitor,False,False
41,0,0.0,0,0.0,3,22.000000,0.000000,0.066667,0.000000,0.6,Feb,1,1,3,2,Returning_Visitor,False,False
42,0,0.0,0,0.0,15,310.166667,0.000000,0.006667,0.000000,0.0,Feb,1,1,4,4,Returning_Visitor,False,False
43,0,0.0,0,0.0,2,34.000000,0.000000,0.050000,0.000000,0.4,Feb,3,2,2,3,Returning_Visitor,False,False
44,0,0.0,0,0.0,4,88.000000,0.000000,0.050000,0.000000,0.0,Feb,4,1,1,3,Returning_Visitor,False,False
45,0,0.0,0,0.0,22,622.250000,0.003030,0.006061,0.000000,0.2,Feb,2,5,1,4,Returning_Visitor,False,False
46,0,0.0,0,0.0,14,222.400000,0.017143,0.057143,0.000000,0.0,Feb,1,1,1,2,Returning_Visitor,False,False
47,0,0.0,0,0.0,3,80.000000,0.066667,0.133333,0.000000,0.2,Feb,3,2,1,3,Returning_Visitor,False,False
48,0,0.0,0,0.0,11,800.833333,0.000000,0.003636,0.000000,0.0,Feb,3,2,1,3,Returning_Visitor,False,False
49,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.6,Feb,2,2,3,2,Returning_Visitor,False,False

In [ ]:
df.columns

Index(['Administrative', 'Administrative_Duration', 'Informational',
       'Informational_Duration', 'ProductRelated', 'ProductRelated_Duration',
       'BounceRates', 'ExitRates', 'PageValues', 'SpecialDay', 'Month',
       'OperatingSystems', 'Browser', 'Region', 'TrafficType', 'VisitorType',
       'Weekend', 'Revenue'],
      dtype='object')

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report


# Convert categorical variables to numerical representations
df = pd.get_dummies(df, columns=["Month", "VisitorType"], drop_first=True)

# Split the data into input features (X) and target variable (y)
X = df.drop(["Revenue"], axis=1)
y = df["Revenue"]

# Step 2: Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 3: Ensemble Learning Model (Random Forest)
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Step 4: Predicting Revenue and Weekend
y_pred = model.predict(X_test)
revenue_predictions = y_pred
weekend_predictions = X_test["Weekend"]

# Step 5: Finding Informational_Duration
informational_duration_predictions = model.predict(X_test)  # Assuming Informational_Duration is predicted using the same features as Revenue and Weekend

# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print(classification_report(y_test, y_pred))

Accuracy: 0.8925385239253852
              precision    recall  f1-score   support

       False       0.91      0.96      0.94      2055
        True       0.74      0.54      0.63       411

    accuracy                           0.89      2466
   macro avg       0.83      0.75      0.78      2466
weighted avg       0.88      0.89      0.89      2466